version: "3.8"

services:
  web:
    container_name: "checklist_api"
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://checklistAdmin:testtest2@db:5432/checklistDb
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
        - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=checklistAdmin
      - POSTGRES_PASSWORD=testtest2
      - POSTGRES_DB=checklistDb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080