"""init

Revision ID: 40e03484c82f
Revises: 
Create Date: 2021-11-01 18:13:02.564025

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '40e03484c82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_date'), 'checklist', ['date'], unique=False)
    op.create_index(op.f('ix_checklist_id'), 'checklist', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_name'), 'checklist', ['name'], unique=False)
    op.create_table('task',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_description'), 'task', ['description'], unique=False)
    op.create_index(op.f('ix_task_done'), 'task', ['done'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_index(op.f('ix_task_risk'), 'task', ['risk'], unique=False)
    op.create_table('taskchecklistlink',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'checklist_id')
    )
    op.create_index(op.f('ix_taskchecklistlink_checklist_id'), 'taskchecklistlink', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_taskchecklistlink_task_id'), 'taskchecklistlink', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskchecklistlink_task_id'), table_name='taskchecklistlink')
    op.drop_index(op.f('ix_taskchecklistlink_checklist_id'), table_name='taskchecklistlink')
    op.drop_table('taskchecklistlink')
    op.drop_index(op.f('ix_task_risk'), table_name='task')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_done'), table_name='task')
    op.drop_index(op.f('ix_task_description'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_checklist_name'), table_name='checklist')
    op.drop_index(op.f('ix_checklist_id'), table_name='checklist')
    op.drop_index(op.f('ix_checklist_date'), table_name='checklist')
    op.drop_table('checklist')
    # ### end Alembic commands ###
