"""init

Revision ID: 46a1ec2f57b5
Revises: 
Create Date: 2021-11-13 22:57:29.702350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '46a1ec2f57b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_creator'), 'album', ['creator'], unique=False)
    op.create_index(op.f('ix_album_genre'), 'album', ['genre'], unique=False)
    op.create_index(op.f('ix_album_id'), 'album', ['id'], unique=False)
    op.create_index(op.f('ix_album_title'), 'album', ['title'], unique=False)
    op.create_table('book',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_creator'), 'book', ['creator'], unique=False)
    op.create_index(op.f('ix_book_genre'), 'book', ['genre'], unique=False)
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_table('movie',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_creator'), 'movie', ['creator'], unique=False)
    op.create_index(op.f('ix_movie_genre'), 'movie', ['genre'], unique=False)
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_table('review',
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_album_id'), 'review', ['album_id'], unique=False)
    op.create_index(op.f('ix_review_book_id'), 'review', ['book_id'], unique=False)
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_index(op.f('ix_review_movie_id'), 'review', ['movie_id'], unique=False)
    op.create_index(op.f('ix_review_rating'), 'review', ['rating'], unique=False)
    op.create_index(op.f('ix_review_text'), 'review', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_text'), table_name='review')
    op.drop_index(op.f('ix_review_rating'), table_name='review')
    op.drop_index(op.f('ix_review_movie_id'), table_name='review')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_index(op.f('ix_review_book_id'), table_name='review')
    op.drop_index(op.f('ix_review_album_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_index(op.f('ix_movie_genre'), table_name='movie')
    op.drop_index(op.f('ix_movie_creator'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_index(op.f('ix_book_genre'), table_name='book')
    op.drop_index(op.f('ix_book_creator'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_album_title'), table_name='album')
    op.drop_index(op.f('ix_album_id'), table_name='album')
    op.drop_index(op.f('ix_album_genre'), table_name='album')
    op.drop_index(op.f('ix_album_creator'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
