"""init

Revision ID: 866a41395f5b
Revises: 
Create Date: 2021-11-01 22:53:54.650160

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '866a41395f5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_template_id'), 'checklist_template', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_template_name'), 'checklist_template', ['name'], unique=False)
    op.create_table('task_template',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_template_description'), 'task_template', ['description'], unique=False)
    op.create_index(op.f('ix_task_template_id'), 'task_template', ['id'], unique=False)
    op.create_index(op.f('ix_task_template_name'), 'task_template', ['name'], unique=False)
    op.create_index(op.f('ix_task_template_risk'), 'task_template', ['risk'], unique=False)
    op.create_table('checklist',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checklist_template_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_checklist_template_id'), 'checklist', ['checklist_template_id'], unique=False)
    op.create_index(op.f('ix_checklist_date'), 'checklist', ['date'], unique=False)
    op.create_index(op.f('ix_checklist_id'), 'checklist', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_name'), 'checklist', ['name'], unique=False)
    op.create_table('task',
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('checklist_template_id', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_template.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_checklist_template_id'), 'task', ['checklist_template_id'], unique=False)
    op.create_index(op.f('ix_task_done'), 'task', ['done'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_task_task_template_id'), 'task', ['task_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_task_template_id'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_done'), table_name='task')
    op.drop_index(op.f('ix_task_checklist_template_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_checklist_name'), table_name='checklist')
    op.drop_index(op.f('ix_checklist_id'), table_name='checklist')
    op.drop_index(op.f('ix_checklist_date'), table_name='checklist')
    op.drop_index(op.f('ix_checklist_checklist_template_id'), table_name='checklist')
    op.drop_table('checklist')
    op.drop_index(op.f('ix_task_template_risk'), table_name='task_template')
    op.drop_index(op.f('ix_task_template_name'), table_name='task_template')
    op.drop_index(op.f('ix_task_template_id'), table_name='task_template')
    op.drop_index(op.f('ix_task_template_description'), table_name='task_template')
    op.drop_table('task_template')
    op.drop_index(op.f('ix_checklist_template_name'), table_name='checklist_template')
    op.drop_index(op.f('ix_checklist_template_id'), table_name='checklist_template')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
